#include "game_map.h"

int world_map[MAP_H][MAP_W] = {
    {WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE},
    {WHITE_TILE, 0, 0, 0, 0, 0, 0, WHITE_TILE, 0, 0, 0, 0, 0, 0, 0, WHITE_TILE},
    {WHITE_TILE, 0, BLACK_TILE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, RED_TILE, 0, WHITE_TILE},
    {WHITE_TILE, 0, 0, 0, WHITE_TILE, WHITE_TILE, 0, WHITE_TILE, WHITE_TILE, 0, WHITE_TILE, WHITE_TILE, 0, 0, 0, WHITE_TILE},
    {WHITE_TILE, 0, 0, WHITE_TILE, 0, 0, 0, 0, 0, 0, 0, 0, WHITE_TILE, 0, 0, WHITE_TILE},
    {WHITE_TILE, 0, 0, WHITE_TILE, 0, BLUE_TILE, 0, 0, 0, GREEN_TILE, 0, 0, WHITE_TILE, 0, 0, WHITE_TILE},
    {WHITE_TILE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, WHITE_TILE},
    {WHITE_TILE, WHITE_TILE, 0, WHITE_TILE, 0, 0, 0, 0, 0, 0, 0, 0, WHITE_TILE, 0, WHITE_TILE, WHITE_TILE},
    {WHITE_TILE, WHITE_TILE, 0, WHITE_TILE, 0, 0, 0, 0, 0, 0, 0, 0, WHITE_TILE, 0, WHITE_TILE, WHITE_TILE},
    {WHITE_TILE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, WHITE_TILE},
    {WHITE_TILE, 0, 0, WHITE_TILE, 0, GREEN_TILE, 0, 0, 0, BLUE_TILE, 0, 0, WHITE_TILE, 0, 0, WHITE_TILE},
    {WHITE_TILE, 0, 0, WHITE_TILE, 0, 0, 0, 0, 0, 0, 0, 0, WHITE_TILE, 0, 0, WHITE_TILE},
    {WHITE_TILE, 0, 0, WHITE_TILE, WHITE_TILE, 0, WHITE_TILE, WHITE_TILE, WHITE_TILE, 0, WHITE_TILE, WHITE_TILE, 0, 0, 0, WHITE_TILE},
    {WHITE_TILE, 0, RED_TILE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, BLACK_TILE, 0, WHITE_TILE},
    {WHITE_TILE, 0, 0, 0, 0, 0, 0, WHITE_TILE, 0, 0, 0, 0, 0, 0, 0, WHITE_TILE},
    {WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE, WHITE_TILE}
};

int get_grid_type(int x, int y){
    if(x < 0 || x > MAP_W || y < 0 || y > MAP_H) return -1;
    return world_map[x][y];
}
